### ISSUE TITLE
Detecting pubkeys in encrypted emails fails the first time

### ISSUE THREAD

**Issue by micahflee** [EFForg/cryptobot-email#18]
If you completely the delete the test gpg homedir, some of the tests fail the first time. The tests that fail are ones where it's parsing an encrypted email, decrypting it, and searching for pubkeys.

```
(env)[micah@bones] (master) ~/eff_projects/cryptobot-email$ rm -rf test/homedir/
(env)[micah@bones] (master) ~/eff_projects/cryptobot-email$ ./test.py 
..FFF.................
======================================================================
FAIL: test_encrypted_pubkey_included_attached_application_pgpkeys (__main__.BotTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 149, in test_encrypted_pubkey_included_attached_application_pgpkeys
    self.assertTrue(msg.pubkey_included)
AssertionError: False is not true

======================================================================
FAIL: test_encrypted_pubkey_included_attached_text_plain (__main__.BotTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 144, in test_encrypted_pubkey_included_attached_text_plain
    self.assertTrue(msg.pubkey_included)
AssertionError: False is not true

======================================================================
FAIL: test_encrypted_pubkey_included_inline (__main__.BotTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 154, in test_encrypted_pubkey_included_inline
    self.assertTrue(msg.pubkey_included)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 22 tests in 5.885s

FAILED (failures=3)
```

But then if you run the same test a second time, it passes. I assume it's because the pubkeys are already in the keyring, but I need to look more into it:

```
(env)[micah@bones] (master) ~/eff_projects/cryptobot-email$ ./test.py 
......................
----------------------------------------------------------------------
Ran 22 tests in 5.507s

OK
```

**Comment by wearpants** [comment]
Following on from comment on #23:

Tests that need external state (files, database, whatever) should create that state in setUp and remove it in tearDown (or via addCleanup). This way each test is guaranteed to run with known initial state; hidden dependencies between tests can cause spurious failures or successes). These problems often manifests when the order of test execution changes (it's not guaranteed to be consistent).  

I think the best approach would be to add `tests/homedir_template` that gets copied fresh to `tests/homedir` in setUp. The template would be added to git (as opposed to the homedir, which is currently gitignore'd).

Still need to figure out what exactly the template should look like of course. ;-) 

There is one test (`GnuPGTest.test_gen_key`) which needs to generate a new key; this should probably use an empty temporary homedir for each run.
