### ISSUE TITLE
self.message_id is not callable (str object)

### ISSUE THREAD

**Issue by frafra** [EFForg/cryptobot-email#38]
```
Traceback (most recent call last):
  File "./bot.py", line 777, in <module>
    main(fingerprint)
  File "./bot.py", line 725, in main
    messages = fetcher.get_all_mail()
  File "./bot.py", line 310, in get_all_mail
    return self.get_imap_mail()
  File "./bot.py", line 299, in get_imap_mail
    message_id=message_id))
  File "./bot.py", line 531, in __init__
    self._parse_for_openpgp()
  File "./bot.py", line 583, in _parse_for_openpgp
    logging.warning("More than one signed part in this message. That's weird... {0}".format(self.message_id()))
TypeError: 'str' object is not callable
```

**Comment by frafra** [comment]
If I replace every self.message_id() with self.message in bot.py, I get this kind of output:

```
WARNING:root:More than one signed part in this message. That's weird... 43732
WARNING:root:More than one signed part in this message. That's weird... 43755
WARNING:root:More than one signed part in this message. That's weird... 44414
```
